import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import AuthProvider from "./providers/auth";
import { Navbar } from "./components/navbar/navbar";
import { IngredientProvider } from "./context/ingredientsContext";
import { Rodape } from "./components/rodape/rodape";
import "./globals.css";


const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className}`}
      >
        <IngredientProvider>
          <AuthProvider>
            <Navbar />
            <div className="flex-1">
              {children}
            </div>
            <Rodape />
          </AuthProvider>
        </IngredientProvider>
      </body>
    </html>
  );
}
