import { Montserrat } from "next/font/google";
import { Rodape } from "../components/rodape/rodape";
const montserrat = Montserrat({ subsets: ["latin"] });
import "../globals.css"

export const metadata = {
    title: 'ADM PAGE',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body
                suppressHydrationWarning={true}
                className={`${montserrat.className}`}
            >

                {children}
                <Rodape />
            </body>
        </html>
    )
}
